### ISSUE TITLE
copy(D:\laragon\www\bgmalaysia\resources\lang/en/auth.php): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by kidino** [akukoder/fortify-tabler-admin#1]
I am getting this error when running `php artisan fortify:tabler`

And it appears I don't have the /lang folder at all. Is it supposed to be there?

**Comment by syahzul** [comment]
For a new Laravel installations, it should be there by default. May I know your Laravel version?

**Comment by kidino** [comment]
Version 9

**Comment by syahzul** [comment]
Issue has been fixed in the latest 1.0.7
