### ISSUE TITLE
Failed to open stream: No such file or directory - Laravel 9

### ISSUE THREAD

**Issue by hakimj96** [akukoder/fortify-tabler-admin#2]
Fortify UI has been installed. Proceeding to install the preset.

   ErrorException 

  copy(/Users/hakimj/source_code/fortify-test/resources/lang/en/auth.php): Failed to open stream: No such file or directory

============================================================================================

Hi, I got this error message after choosing layout, position and etc.. (php artisan fortify:tabler). Currently using Laravel 9 fresh installation

<img width="1071" alt="Screenshot 2022-04-14 at 4 11 56 PM" src="https://user-images.githubusercontent.com/27670318/163342975-5ba51496-5e06-4fa0-98cd-970e7854ba8b.png">

**Comment by syahzul** [comment]
Issue has been fixed in the latest 1.0.7
