### ISSUE TITLE
Username is required (auth.register)

### ISSUE THREAD

**Issue by hakimj96** [akukoder/fortify-tabler-admin#4]
Register auth require name, username, email and password. First time register I got "Username is required" but the name field is already filled. So what I did was by adding one more input for username, and walla, can register!

[here is the image Before adding one more input field]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/27670318/163504198-5618b0ae-0c83-42cc-ab4e-35595943e241.png">

[here is the image After adding one more input field]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/27670318/163504105-c0d0f1c5-e6d8-4e85-ae63-db756d52fe3c.png">

but still cannot view dashboard because of another error [Undefined variable $slot]. Maybe I forgot something, let me check first

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/27670318/163504292-21c9ed63-0781-439b-a366-2dcaa8ee25ca.png">

**Comment by syahzul** [comment]
It seems that I've missed that part. I'll push the fix later.

Thanks.
