### ISSUE TITLE
I want to run in panel prefix

### ISSUE THREAD

**Issue by neonturk** [akukoder/fortify-tabler-admin#5]
Hi,
I want to run it in the panel prefix but when I set the prefix in the route many things don't work

**Comment by syahzul** [comment]
Can you share me the error page and your route file?

**Comment by neonturk** [comment]
![image](https://user-images.githubusercontent.com/1378487/163804222-1b7ee897-bfa8-4d00-a2d9-08b6e5c0c197.png)
![image](https://user-images.githubusercontent.com/1378487/163804502-1104d13a-7b18-4fea-8051-44e87d50a0ad.png)

In addition, the links of the sample pages in the menu do not work.
![image](https://user-images.githubusercontent.com/1378487/163804635-99acb212-a071-4b43-8019-6739b5f9ba22.png)

**Comment by syahzul** [comment]
You can edit ```/resources/views/components/navbar-item-user.blade.php```, line 14 and find ```url('profile')``` and change to ```route('profile')```. This should fix the problem.

I'll push the fix later.

Thanks.
