### ISSUE TITLE
Edit profile avatar is not responsive

### ISSUE THREAD

**Issue by hakimj96** [akukoder/fortify-tabler-admin#9]
Hello! Just wanted to let you know, profile avatar in edit profile & account is not responsive. Ive fixed on my local but just mentioning :)

<img width="654" alt="image" src="https://user-images.githubusercontent.com/27670318/164154931-10eae299-8474-4dd7-8898-90d40eecf088.png">

**Comment by syahzul** [comment]
Thanks, I will fix and push update later.
